server {
	host 0.0.0.0
	port 8080
	server_name webserver.com www.webserver.com
	client_max_body_size 2048576

	error_page 404 /www/html/errors/404.html
	error_page 500 /www/html/errors/500.html


	route /*.py {
		methods POST GET
		root ./www/cgi-bin
	}
	
	route / {
		methods GET
		root ./www/html
		default_file index.html
		directory_listing off
	}

	route /*.bla {
		methods POST GET
		root ./www
		cgi_handler ./ubuntu_cgi_tester
	}

	route /post_body {
		methods POST
		root ./www
		client_max_body_size 100
	}

	route /post/test {
        methods POST
        root ./www
        client_max_body_size 1024
    }

	route /directory {
		methods GET
		root ./YoupiBanane
		default_file youpi.bad_extension
		directory_listing on
	}

}
