user  www-data;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout  65;

      upstream php-fpm {
       server wordpress:9000;  # php-fpm lives in the WordPress container
    }

    # HTTPS only (no port 80 server block)
    server {
        listen              443 ssl http2;
        server_name         rghisoiu.42.fr;
        root                /var/www/html;
        index               index.php index.html;

        # TLS v1.2 / v1.3 only
        ssl_certificate     /etc/nginx/ssl/selfsigned.crt;
        ssl_certificate_key /etc/nginx/ssl/selfsigned.key;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

       location ~ \.php$ {
	   include        fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
           fastcgi_pass   php-fpm;
       }

        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options DENY;
        add_header X-XSS-Protection "1; mode=block";
    }
}